CREATE INDEX IF NOT EXISTS idx_inventory_item_category ON "InventoryItem" ("categoryId");
CREATE INDEX IF NOT EXISTS idx_inventory_item_active ON "InventoryItem" ("isActive");
CREATE INDEX IF NOT EXISTS idx_inventory_batch_status ON "InventoryBatch" ("status");
CREATE INDEX IF NOT EXISTS idx_inventory_batch_item ON "InventoryBatch" ("itemId");
CREATE INDEX IF NOT EXISTS idx_inventory_batch_warehouse ON "InventoryBatch" ("warehouseId");
CREATE INDEX IF NOT EXISTS idx_stock_transaction_type ON "StockTransaction" ("type");
CREATE INDEX IF NOT EXISTS idx_stock_transaction_batch ON "StockTransaction" ("batchId");
CREATE INDEX IF NOT EXISTS idx_stock_transaction_date ON "StockTransaction" ("createdAt");
CREATE INDEX IF NOT EXISTS idx_resource_request_status ON "ResourceRequest" ("status");
CREATE INDEX IF NOT EXISTS idx_purchase_order_status ON "PurchaseOrder" ("status");
CREATE INDEX IF NOT EXISTS idx_waste_record_type ON "WasteRecord" ("wasteType");
CREATE INDEX IF NOT EXISTS idx_notification_user_read ON "Notification" ("userId", "isRead");
CREATE INDEX IF NOT EXISTS idx_audit_log_entity ON "AuditLog" ("entity", "entityId");
CREATE INDEX IF NOT EXISTS idx_audit_log_date ON "AuditLog" ("createdAt");
